import { existsSync } from 'node:fs';
import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';

import formatString from '@robertsspaceindustries/sub';
import { pascalCase } from 'change-case';
import { compile } from 'json-schema-to-typescript';
import ky from 'ky';
import prettier from 'prettier';

if (existsSync('generated')) await rm('generated', { recursive: true });
await mkdir('generated');

const environment = process.env.DATA_ENV || process.env.NODE_ENV;
const version = process.argv[2];
const prefixUrl = `https://public-stats-data.multicrew.dev/${environment}/${version}`;
const dataApi = ky.create({ prefixUrl });

console.log(`Environment: ${environment}  Version: ${version}`);

export const { files } = await dataApi
  .get('index.json')
  .json<{ files: string[] }>();

const prettierConfig = await prettier.resolveConfig('.prettierrc');
let header = '/* eslint-disable */\n';
header += '/**\n';
header += ' * This file was automatically generated by scripts/generate.mts.\n';
header += ' * DO NOT MODIFY IT BY HAND.\n';
header += ' */\n';
header += '\n';

let sseSource = await readFile('scripts/generate/sse.ts', 'utf-8');
sseSource = formatString(sseSource, { environment, version });
await writeFile('generated/sse.ts', header + sseSource, 'utf-8');

await Promise.all(
  files.map(async (dataFile) => {
    const fileBasename = path.basename(dataFile, '.json');
    const schemaFile = `${fileBasename}.schema.json`;
    const basename = fileBasename.replace(/[^a-zA-Z0-9]/g, '_');
    const pascalBasename = pascalCase(basename);

    const dataResponse = await dataApi.head(dataFile);
    if (!dataResponse.ok) return;

    const schemaResponse = await dataApi.get(schemaFile);
    if (!schemaResponse.body) return;

    const schema = JSON.parse(await schemaResponse.text());

    const compiledTypes = await compile(schema, pascalBasename, {
      bannerComment: '',
      format: false,
      additionalProperties: false,
    });

    let outputContent = header;
    outputContent += `import ky from 'ky';\n`;
    outputContent += '\n';
    outputContent += `import { sse } from './sse';\n`;
    outputContent += '\n';
    outputContent += compiledTypes;
    outputContent += '\n';
    outputContent += `async function fetch${pascalBasename}() {\n`;
    outputContent += `  const response = await ky.get('${prefixUrl}/${dataFile}');\n`;
    outputContent += `  const data = await response.json<Default>();\n`;
    outputContent += `  \n`;
    outputContent += `  if ("$schema" in data) delete data.$schema;\n`;
    outputContent += `  if ("$version" in data) delete data.$version;\n`;
    outputContent += `  \n`;
    outputContent += `  console.log('Fetched ${dataFile}', response.headers.get('etag'));\n`;
    outputContent += `  \n`;
    outputContent += `  return data;\n`;
    outputContent += `}\n`;
    outputContent += '\n';
    outputContent += `let ${basename} = await fetch${pascalBasename}();\n`;
    outputContent += `sse.on('${dataFile}', async () => {\n`;
    outputContent += `  ${basename} = await fetch${pascalBasename}();\n`;
    outputContent += `});\n`;
    outputContent += '\n';
    outputContent += `export const get${pascalBasename} = () => ${basename};\n`;

    const formattedContent = await prettier.format(outputContent, {
      ...prettierConfig!,
      parser: 'typescript',
    });

    await writeFile(`generated/${basename}.ts`, formattedContent, 'utf-8');
  }),
);
