import { existsSync } from 'node:fs';
import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';

import formatString from '@robertsspaceindustries/sub';
import { pascalCase } from 'change-case';
import { compile } from 'json-schema-to-typescript';
import ky from 'ky';
import prettier from 'prettier';

if (existsSync('generated')) await rm('generated', { recursive: true });
await mkdir('generated');

const environment = process.env.DATA_ENV || process.env.NODE_ENV;
const version = process.argv[2];
const prefixUrl = `https://public-stats-data.multicrew.dev/${environment}/${version}`;
const dataApi = ky.create({ prefixUrl });

console.log(`Environment: ${environment}  Version: ${version}`);

export const { files } = await dataApi
  .get('index.json')
  .json<{ files: string[] }>();

const prettierConfig = await prettier.resolveConfig('.prettierrc');
let header = '/* eslint-disable */\n';
header += '/**\n';
header += ' * This file was automatically generated by scripts/generate.mts.\n';
header += ' * DO NOT MODIFY IT BY HAND.\n';
header += ' */\n';
header += '\n';

let sseSource = await readFile('scripts/generate/sse.ts', 'utf-8');
sseSource = formatString(sseSource, { environment, version });
await writeFile('generated/sse.ts', header + sseSource, 'utf-8');

await Promise.all(
  files.map(async (dataFile) => {
    const fileBasename = path.basename(dataFile, '.json');
    const schemaFile = `${fileBasename}.schema.json`;
    const basename = fileBasename.replace(/[^a-zA-Z0-9]/g, '_');
    const pascalBasename = pascalCase(basename);

    const dataResponse = await dataApi.head(dataFile);
    if (!dataResponse.ok) return;

    const schemaResponse = await dataApi.get(schemaFile);
    if (!schemaResponse.body) return;

    const schema = JSON.parse(await schemaResponse.text());

    const compiledTypes = await compile(schema, pascalBasename, {
      bannerComment: '',
      format: false,
      additionalProperties: false,
    });

    let outputContent = header;
    outputContent += `import { existsSync } from 'node:fs';\n`;
    outputContent += `import { mkdir, readFile, writeFile } from 'node:fs/promises';\n`;
    outputContent += `import ky, { HTTPError } from 'ky';\n`;
    outputContent += '\n';
    outputContent += `import { sse } from './sse';\n`;
    outputContent += '\n';
    outputContent += compiledTypes;
    outputContent += '\n';
    outputContent += `const cacheDir = '.cache';\n`;
    outputContent += `const cacheFile = \`\${cacheDir}/${basename}.json\`;\n`;
    outputContent += '\n';
    outputContent += `interface CacheEntry {\n`;
    outputContent += `  etag: string;\n`;
    outputContent += `  data: Default;\n`;
    outputContent += `}\n`;
    outputContent += '\n';
    outputContent += `async function fetch${pascalBasename}() {\n`;
    outputContent += `  if (!existsSync(cacheDir)) await mkdir(cacheDir, { recursive: true });\n`;
    outputContent += `  \n`;
    outputContent += `  let cached: CacheEntry | null = null;\n`;
    outputContent += `  if (existsSync(cacheFile)) {\n`;
    outputContent += `    try {\n`;
    outputContent += `      cached = JSON.parse(await readFile(cacheFile, 'utf-8'));\n`;
    outputContent += `    } catch {}\n`;
    outputContent += `  }\n`;
    outputContent += `  \n`;
    outputContent += `  const headers: Record<string, string> = {};\n`;
    outputContent += `  if (cached?.etag) headers['If-None-Match'] = cached.etag;\n`;
    outputContent += `  \n`;
    outputContent += `  try {\n`;
    outputContent += `    const response = await ky.get('${prefixUrl}/${dataFile}', { headers, throwHttpErrors: true });\n`;
    outputContent += `    const data = await response.json<Default>();\n`;
    outputContent += `    const etag = response.headers.get('etag') || '';\n`;
    outputContent += `    \n`;
    outputContent += `    if ("$schema" in data) delete data.$schema;\n`;
    outputContent += `    if ("$version" in data) delete data.$version;\n`;
    outputContent += `    \n`;
    outputContent += `    await writeFile(cacheFile, JSON.stringify({ etag, data }), 'utf-8');\n`;
    outputContent += `    console.log('Fetched ${dataFile}', etag);\n`;
    outputContent += `    \n`;
    outputContent += `    return data;\n`;
    outputContent += `  } catch (error) {\n`;
    outputContent += `    if (error instanceof HTTPError && error.response.status === 304 && cached) {\n`;
    outputContent += `      console.log('Using cached ${dataFile}', cached.etag);\n`;
    outputContent += `      return cached.data;\n`;
    outputContent += `    }\n`;
    outputContent += `    throw error;\n`;
    outputContent += `  }\n`;
    outputContent += `}\n`;
    outputContent += '\n';
    outputContent += `let ${basename} = await fetch${pascalBasename}();\n`;
    outputContent += `sse.on('${dataFile}', async () => {\n`;
    outputContent += `  ${basename} = await fetch${pascalBasename}();\n`;
    outputContent += `});\n`;
    outputContent += '\n';
    outputContent += `export const get${pascalBasename} = () => ${basename};\n`;

    const formattedContent = await prettier.format(outputContent, {
      ...prettierConfig!,
      parser: 'typescript',
    });

    await writeFile(`generated/${basename}.ts`, formattedContent, 'utf-8');
  }),
);
