import { existsSync } from 'node:fs';
import { mkdir, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';

import * as changeCase from 'change-case';
import { compile } from 'json-schema-to-typescript';
import ky from 'ky';
import prettier from 'prettier';

if (existsSync('generated')) await rm('generated', { recursive: true });
await mkdir('generated');

const version = process.argv[2];
const prefixUrl = `https://public-stats-data.multicrew.dev/${process.env.NODE_ENV}/${version}`;
const dataApi = ky.create({ prefixUrl });

export const { files } = await dataApi
  .get('index.json')
  .json<{ files: string[] }>();

const prettierConfig = await prettier.resolveConfig('.prettierrc');

await Promise.all(
  files.map(async (dataFile) => {
    const basename = path.basename(dataFile, '.json');
    const schemaFile = `${basename}.schema.json`;

    const dataResponse = await dataApi.head(dataFile);
    if (!dataResponse.ok) return;

    const schemaResponse = await dataApi.get(schemaFile);
    if (!schemaResponse.body) return;

    const schema = JSON.parse(await schemaResponse.text());

    const compiledTypes = await compile(
      schema,
      changeCase.pascalCase(basename),
      {
        bannerComment: '',
        format: false,
        additionalProperties: false,
      },
    );

    let outputContent = '/* eslint-disable */\n';
    outputContent += '/**\n';
    outputContent +=
      ' * This file was automatically generated by scripts/generate.mts.\n';
    outputContent += ' * DO NOT MODIFY IT BY HAND.\n';
    outputContent += ' */\n';
    outputContent += '\n';

    outputContent += `import ky from 'ky';\n`;
    outputContent += '\n';
    outputContent += compiledTypes;
    outputContent += '\n';
    outputContent += `const ${basename}: Default = await ky.get('${`${prefixUrl}/${dataFile}`}').json();\n`;
    outputContent += '\n';
    outputContent += `export default ${basename};\n`;

    const formattedContent = await prettier.format(outputContent, {
      ...prettierConfig!,
      parser: 'typescript',
    });

    await writeFile(`generated/${basename}.ts`, formattedContent, 'utf-8');
  }),
);
