import { existsSync } from 'node:fs';
import { mkdir, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';

import { pascalCase } from 'change-case';
import { compile } from 'json-schema-to-typescript';
import ky from 'ky';
import prettier from 'prettier';

if (existsSync('generated')) await rm('generated', { recursive: true });
await mkdir('generated');

const version = process.argv[2];
const prefixUrl = `https://public-stats-data.multicrew.dev/${process.env.NODE_ENV}/${version}`;
const dataApi = ky.create({ prefixUrl });

export const { files } = await dataApi
  .get('index.json')
  .json<{ files: string[] }>();

const prettierConfig = await prettier.resolveConfig('.prettierrc');

await Promise.all(
  files.map(async (dataFile) => {
    const fileBasename = path.basename(dataFile, '.json');
    const schemaFile = `${fileBasename}.schema.json`;
    const basename = fileBasename.replace(/[^a-zA-Z0-9]/g, '_');
    const pascalBasename = pascalCase(basename);

    const dataResponse = await dataApi.head(dataFile);
    if (!dataResponse.ok) return;

    const schemaResponse = await dataApi.get(schemaFile);
    if (!schemaResponse.body) return;

    const schema = JSON.parse(await schemaResponse.text());

    const compiledTypes = await compile(schema, pascalBasename, {
      bannerComment: '',
      format: false,
      additionalProperties: false,
    });

    let outputContent = '/* eslint-disable */\n';
    outputContent += '/**\n';
    outputContent +=
      ' * This file was automatically generated by scripts/generate.mts.\n';
    outputContent += ' * DO NOT MODIFY IT BY HAND.\n';
    outputContent += ' */\n';
    outputContent += '\n';

    outputContent += `import ky from 'ky';\n`;
    outputContent += `import { setIntervalAsync } from 'set-interval-async';\n`;
    outputContent += '\n';
    outputContent += compiledTypes;
    outputContent += '\n';
    outputContent += `async function fetch${pascalBasename}() {\n`;
    outputContent += `  const data = ky.get('${prefixUrl}/${dataFile}').json<Default>();\n`;
    outputContent += `  \n`;
    outputContent += `  if ("$schema" in data) delete data.$schema;\n`;
    outputContent += `  if ("$version" in data) delete data.$version;\n`;
    outputContent += `  \n`;
    outputContent += `  console.log('Fetched ${dataFile}');\n`;
    outputContent += `  \n`;
    outputContent += `  return data;\n`;
    outputContent += `}\n`;
    outputContent += '\n';
    outputContent += `let ${basename} = await fetch${pascalBasename}();\n`;
    outputContent += `setIntervalAsync(async () => {\n`;
    outputContent += `  ${basename} = await fetch${pascalBasename}();\n`;
    outputContent += `}, 30 * 60 * 1_000);\n`;
    outputContent += '\n';
    outputContent += `export const get${pascalBasename} = () => ${basename};\n`;

    const formattedContent = await prettier.format(outputContent, {
      ...prettierConfig!,
      parser: 'typescript',
    });

    await writeFile(`generated/${basename}.ts`, formattedContent, 'utf-8');
  }),
);
