import { MEDIA_PREFIX } from '@/env';

const newShells: Record<string, string> = {
  HESH: 'hesh',
  'PROXIMITY FUZE': 'proximity-fuze',
  CLUSTER: 'cluster',
  'OTA ATGM': 'ota-atgm',
  APDS: 'apds',
  'TIME FUZE': 'time-fuze',
  APBC: 'apbc',
  MG: 'mg',
  HE: 'he',
  APHEBC: 'aphebc',
  THERMOBARIC: 'thermobaric',
  APHEC: 'aphec',
  ATGM: 'atgm',
  'CANISTER SHOT': 'canister-shot',
  SAPHE: 'saphe',
  'Top Attack Shell': 'top-attack-shell',
  HEAT: 'heat',
  'ATGM TANDEM': 'atgm-tandem',
  'DU APFSDS': 'du-apfsds',
  APHE: 'aphe',
  AAM: 'aam',
  HVAP: 'hvap',
  APCBC: 'apcbc',
  'APFSDS ANTI-ERA': 'apfsds-anti-era',
  'CANISTER APFSDS': 'canister-apfsds',
  'APDS (E)': 'apds-e',
  'KINETIC ATGM': 'kinetic-atgm',
  APC: 'apc',
  'F&F Top Attack ATGM': 'ff-top-attack-atgm',
  'APDS (C)': 'apds-c',
  'DU APFSDS ANTI-ERA': 'du-apfsds-anti-era',
  APHECBC: 'aphecbc',
  APCR: 'apcr',
  'APFSDS INCENDIARY ANTI-ERA': 'apfsds-incendiary-anti-era',
  APFSDS: 'apfsds',
  ROCKET: 'rocket',
  'ATGM HE': 'atgm-he',
  'HEAT-FS': 'heat-fs',
  SMOKE: 'smoke',
  'ATGM-VT': 'atgm-vt',
  'AAM-VT': 'aam-vt',
  INCENDIARY: 'incendiary',
  'SMOKE SHELL': 'smoke-shell',
  AP: 'ap',
};

export function getShellIcon(displayType: string) {
  if (!newShells[displayType]) return null;
  return `${MEDIA_PREFIX}/assets/icons/shells/${newShells[displayType]}.png`;
}
