name: Update Shells

on:
  schedule:
    - cron: '10 0 * * 0'
  workflow_dispatch:

jobs:
  update-shells:
    runs-on: ubuntu-latest
    outputs:
      changes_detected: ${{ steps.check_changes.outputs.changes_detected }}
    strategy:
      matrix:
        environment:
          - name: Sunny Valley
            universe_id: '3221676855'
            place_id: '8421780146'
            data_path: './data/shells/8421780146.json'
          - name: Multicrew Tank Combat
            universe_id: '3546912119'
            place_id: '9520328730'
            data_path: './data/shells/9520328730.json'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup git
        uses: fregante/setup-git-user@v2

      - name: Execute script
        uses: grand-hawk/action-roblox-luau-execution@1.0.0
        with:
          roblox_api_key: ${{ secrets.ROBLOX_LUAU_EXECUTION_API_KEY }}
          universe_id: ${{ matrix.environment.universe_id }}
          place_id: ${{ matrix.environment.place_id }}
          luau_file: './scripts/shells.luau'
          output_file: 'script-execution-output.json'

      - name: Process JSON output
        run: jq ".[0]" "./script-execution-output.json" > "${{ matrix.environment.data_path }}"

      - name: Check for data changes
        id: check_changes
        run: |
          git fetch origin dev
          if ! git diff --quiet origin/dev -- "${{ matrix.environment.data_path }}"; then
            echo "true" > changes_detected.txt
          else
            echo "false" > changes_detected.txt
          fi
        shell: bash

      - name: Set output
        id: set_output
        run: echo "changes_detected=$(cat changes_detected.txt)" >> "$GITHUB_ENV"

  push-changes:
    runs-on: ubuntu-latest
    needs: update-shells
    if: needs.update-shells.outputs.changes_detected == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: dev

      - name: Setup git
        uses: fregante/setup-git-user@v2

      - name: Commit and push to dev and prod
        run: |
          for branch in dev prod; do
            git checkout $branch
            git pull origin $branch
            git add ./data/shells/**
            git commit -m "Update shells data"
            git push origin $branch
          done
