name: Update Shells

on:
  schedule:
    - cron: '15 0 * * 0'
  workflow_dispatch:

jobs:
  update-and-push-shells:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        environment:
          - name: SunnyValley
            universe_id: '3221676855'
            place_id: '8421780146'
            data_path: './data/shells/8421780146.json'
          - name: MulticrewTankCombat
            universe_id: '3546912119'
            place_id: '9520328730'
            data_path: './data/shells/9520328730.json'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: fregante/setup-git-user@v2

      - run: |
          git fetch --all
          git checkout dev
          git pull --rebase origin dev --autostash

      - uses: grand-hawk/action-roblox-luau-execution@v1
        with:
          roblox_api_key: ${{ secrets.ROBLOX_LUAU_EXECUTION_API_KEY }}
          universe_id: ${{ matrix.environment.universe_id }}
          place_id: ${{ matrix.environment.place_id }}
          luau_file: './scripts/shells.luau'
          output_file: 'script-execution-output.json'

      - run: |
          jq ".[0]" "./script-execution-output.json" > "${{ matrix.environment.data_path }}"
          rm script-execution-output.json

      - name: Check for data changes
        id: check_changes
        run: |
          if ! git diff --quiet origin/dev -- "${{ matrix.environment.data_path }}"; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Create branch and push changes
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          BRANCH_NAME="workflow/update-shells-${{ github.run_id }}-${{ matrix.environment.name }}"
          git checkout -b "$BRANCH_NAME"
          git add "${{ matrix.environment.data_path }}"
          git commit -m "Update shells data for ${{ matrix.environment.name }}"
          git push origin "$BRANCH_NAME" --force-with-lease

          git checkout dev
          git pull --rebase origin dev --autostash
          git rebase "$BRANCH_NAME"
          git push origin dev --force-with-lease

          git checkout prod
          git pull --rebase origin prod --autostash
          COMMIT_HASH=$(git rev-parse "$BRANCH_NAME")
          git cherry-pick -n "$COMMIT_HASH"
          git commit -m "Update shells data for ${{ matrix.environment.name }}"
          git push origin prod --force-with-lease

          git push origin --delete "$BRANCH_NAME"
