name: Update KDR Data

on:
  schedule:
    - cron: '0 3 * * *' # Runs daily at 03:00 UTC
  workflow_dispatch:

jobs:
  update-kdr-data:
    runs-on: ubuntu-latest
    outputs:
      changes_detected: ${{ steps.check_changes.outputs.changes_detected }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup git
        uses: fregante/setup-git-user@v2

      - uses: pnpm/action-setup@v4.0.0
        with:
          version: 9

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Update KDR data
        run: pnpm tsx scripts/updateData-kdr.mts
        env:
          INSIGHTS_API_URL: ${{ secrets.INSIGHTS_API_URL }}
          INSIGHTS_API_AUTH: ${{ secrets.INSIGHTS_API_AUTH }}

      - name: Check for data changes
        id: check_changes
        run: |
          git fetch origin dev
          git diff --exit-code ./data/kdr/ || echo "changes_detected=true" >> $GITHUB_ENV
          echo "::set-output name=changes_detected::$(git diff --quiet ./data/kdr/ || echo true)"

  push-changes:
    runs-on: ubuntu-latest
    needs: update-kdr-data
    if: needs.update-kdr-data.outputs.changes_detected == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: dev

      - name: Setup git
        uses: fregante/setup-git-user@v2

      - name: Commit and push to dev and prod
        run: |
          for branch in dev prod; do
            git checkout $branch
            git pull origin $branch
            git add ./data/kdr/**
            git commit -m "Update KDR data"
            git push origin $branch
          done
