name: Update Winrate Data

on:
  schedule:
    - cron: '5 */12 * * *' # Runs every 12 hours
  workflow_dispatch:

jobs:
  update-winrate-data:
    runs-on: ubuntu-latest
    outputs:
      changes_detected: ${{ steps.check_changes.outputs.changes_detected }}
      temp_branch: ${{ steps.create_branch.outputs.temp_branch }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensure full history

      - name: Setup git
        uses: fregante/setup-git-user@v2

      - uses: pnpm/action-setup@v4.0.0
        with:
          version: 9

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Update winrate data
        run: pnpm tsx scripts/updateData-winrate.mts
        env:
          INSIGHTS_API_URL: ${{ secrets.INSIGHTS_API_URL }}
          INSIGHTS_API_AUTH: ${{ secrets.INSIGHTS_API_AUTH }}

      - name: Check for data changes
        id: check_changes
        run: |
          git fetch origin dev
          if ! git diff --quiet origin/dev -- ./data/winrate/; then
            echo "changes_detected=true" >> $GITHUB_ENV
            echo "true" > changes_detected.txt
          else
            echo "changes_detected=false" >> $GITHUB_ENV
            echo "false" > changes_detected.txt
          fi

      - name: Create temporary branch
        id: create_branch
        if: env.changes_detected == 'true'
        run: |
          BRANCH_NAME="workflow/update-winrate-data-${{ github.run_id }}"
          git checkout -b $BRANCH_NAME
          git add ./data/winrate/
          git commit -m "Update winrate data"
          git push origin $BRANCH_NAME
          echo "temp_branch=$BRANCH_NAME" >> $GITHUB_ENV

  push-changes:
    runs-on: ubuntu-latest
    needs: update-winrate-data
    if: needs.update-winrate-data.outputs.changes_detected == 'true'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ needs.update-winrate-data.outputs.temp_branch }}

      - name: Setup git
        uses: fregante/setup-git-user@v2

      - name: Merge into dev and prod
        run: |
          TEMP_BRANCH=${{ needs.update-winrate-data.outputs.temp_branch }}
          for branch in dev prod; do
            git checkout $branch
            git pull origin $branch
            git merge --no-ff $TEMP_BRANCH -m "Merge updated winrate data"
            git push origin $branch
          done

      - name: Delete temporary branch
        run: |
          git push origin --delete ${{ needs.update-winrate-data.outputs.temp_branch }}
